# Basic Information 
title: Sandhya Saravanan
position: Research Fellow
affiliation: Microsoft Research, India
email: sandhyasaravanan978 (at) gmail (dot) com

# Search Engine Optimization (SEO)
keywords: minimal light
canonical: https://minimal-light-theme-mpi-inf.yliu.me/
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.

# The option is used to enable the MPI Informatics template.
#enable_mpi_logo: true

# The option is used to show the last update time.
#enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?authuser=1&user=oCWbckYAAAAJ
cv_link: assets/files/sandhya_CV.pdf
github_link: https://github.com/sandy9999
linkedin: https://www.linkedin.com/in/sandhyasaravanan/

# Images 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
enable_footnote: true

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
